const Sequelize = require("sequelize");
const conn = require("../../database/database");
const Clientes = require("../../Clientes/Clientes");
const Moldes = require("../../Moldes/Moldes");
const Maquinas = require("../../Maquinas/Maquinas");
const Produtos = require("../../Produtos/Produtos");
const MateriaPrima = require("../../MateriaPrima/MateriasPrimas");

const FichaPastoreInjetores = conn.define('injetores_pastore',{

   maq:{
      type: Sequelize.INTEGER,
      model: 'maquinas', // <<< Note, its table's name, not object name
      key: 'id'
   },
   cilindro1: {type: Sequelize.FLOAT, allowNull: true},
   cilindro2: {type: Sequelize.FLOAT, allowNull: true},
   cilindro3: {type: Sequelize.FLOAT, allowNull: true},
   cilindro4: {type: Sequelize.FLOAT, allowNull: true},
   cilindro5: {type: Sequelize.FLOAT, allowNull: true},
   cilindro6: {type: Sequelize.FLOAT, allowNull: true},
   cilindro7: {type: Sequelize.FLOAT, allowNull: true},

   posComut: {type: Sequelize.FLOAT, allowNull: true},
   posInjecao1: {type: Sequelize.FLOAT, allowNull: true},
   posInjecao2: {type: Sequelize.FLOAT, allowNull: true},
   posInjecao3: {type: Sequelize.FLOAT, allowNull: true},
   posInjecao4: {type: Sequelize.FLOAT, allowNull: true},
   posInjecao5: {type: Sequelize.FLOAT, allowNull: true},
   presComut: {type: Sequelize.FLOAT, allowNull: true},
   presInjecao1: {type: Sequelize.FLOAT, allowNull: true},
   presInjecao2: {type: Sequelize.FLOAT, allowNull: true},
   presInjecao3: {type: Sequelize.FLOAT, allowNull: true},
   presInjecao4: {type: Sequelize.FLOAT, allowNull: true},
   presInjecao5: {type: Sequelize.FLOAT, allowNull: true},
   fluxoInjecao1: {type: Sequelize.FLOAT, allowNull: true},
   fluxoInjecao2: {type: Sequelize.FLOAT, allowNull: true},
   fluxoInjecao3: {type: Sequelize.FLOAT, allowNull: true},
   fluxoInjecao4: {type: Sequelize.FLOAT, allowNull: true},
   fluxoInjecao5: {type: Sequelize.FLOAT, allowNull: true},
   tempoDisparo:  {type: Sequelize.FLOAT, allowNull: true},
   pressaoInj:  {type: Sequelize.FLOAT, allowNull: true},

   presRecalque1: {type: Sequelize.FLOAT, allowNull: true},
   presRecalque2: {type: Sequelize.FLOAT, allowNull: true},
   presRecalque3: {type: Sequelize.FLOAT, allowNull: true},
   presRecalque4: {type: Sequelize.FLOAT, allowNull: true},
   presRecalque5: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecalque1: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecalque2: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecalque3: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecalque4: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecalque5: {type: Sequelize.FLOAT, allowNull: true},
   tempoRecalque1: {type: Sequelize.FLOAT, allowNull: true},
   tempoRecalque2: {type: Sequelize.FLOAT, allowNull: true},
   tempoRecalque3: {type: Sequelize.FLOAT, allowNull: true},
   tempoRecalque4: {type: Sequelize.FLOAT, allowNull: true},
   tempoRecalque5: {type: Sequelize.FLOAT, allowNull: true},

   partDosagem1: {type: Sequelize.FLOAT, allowNull: true},
   partDosagem2: {type: Sequelize.FLOAT, allowNull: true},
   partDosagem3: {type: Sequelize.FLOAT, allowNull: true},
   partDosagem4: {type: Sequelize.FLOAT, allowNull: true},
   partDosagem5: {type: Sequelize.FLOAT, allowNull: true},
   presDosagem1: {type: Sequelize.FLOAT, allowNull: true},
   presDosagem2: {type: Sequelize.FLOAT, allowNull: true},
   presDosagem3: {type: Sequelize.FLOAT, allowNull: true},
   presDosagem4: {type: Sequelize.FLOAT, allowNull: true},
   presDosagem5: {type: Sequelize.FLOAT, allowNull: true},
   fluxoDosagem1: {type: Sequelize.FLOAT, allowNull: true},
   fluxoDosagem2: {type: Sequelize.FLOAT, allowNull: true},
   fluxoDosagem3: {type: Sequelize.FLOAT, allowNull: true},
   fluxoDosagem4: {type: Sequelize.FLOAT, allowNull: true},
   fluxoDosagem5: {type: Sequelize.FLOAT, allowNull: true},
   CPDosagem1: {type: Sequelize.FLOAT, allowNull: true},
   CPDosagem2: {type: Sequelize.FLOAT, allowNull: true},
   CPDosagem3: {type: Sequelize.FLOAT, allowNull: true},
   CPDosagem4: {type: Sequelize.FLOAT, allowNull: true},
   CPDosagem5: {type: Sequelize.FLOAT, allowNull: true},
   tempoDosagem: {type: Sequelize.FLOAT, allowNull: true},

   antesPos: {type: Sequelize.FLOAT, allowNull: true},
   antesPres: {type: Sequelize.FLOAT, allowNull: true},
   antesFluxo: {type: Sequelize.FLOAT, allowNull: true},
   antesTempo: {type: Sequelize.FLOAT, allowNull: true},
   depoisPos: {type: Sequelize.FLOAT, allowNull: true},
   depoisPres: {type: Sequelize.FLOAT, allowNull: true},
   depoisFluxo: {type: Sequelize.FLOAT, allowNull: true},
   depoisTempo: {type: Sequelize.FLOAT, allowNull: true},

   posFecha1: {type: Sequelize.FLOAT, allowNull: true},
   posFecha2: {type: Sequelize.FLOAT, allowNull: true},
   posFecha3: {type: Sequelize.FLOAT, allowNull: true},
   protMPos: {type: Sequelize.FLOAT, allowNull: true},
   AltaPresPos: {type: Sequelize.FLOAT, allowNull: true},
   presFecha1: {type: Sequelize.FLOAT, allowNull: true},
   presFecha2: {type: Sequelize.FLOAT, allowNull: true},
   presFecha3: {type: Sequelize.FLOAT, allowNull: true},
   protMPres: {type: Sequelize.FLOAT, allowNull: true},
   AltaPresPres: {type: Sequelize.FLOAT, allowNull: true},
   fluxoFecha1: {type: Sequelize.FLOAT, allowNull: true},
   fluxoFecha2: {type: Sequelize.FLOAT, allowNull: true},
   fluxoFecha3: {type: Sequelize.FLOAT, allowNull: true},
   protMFluxo: {type: Sequelize.FLOAT, allowNull: true},
   AltaPresFluxo: {type: Sequelize.FLOAT, allowNull: true},
   tempoProtMolde: {type: Sequelize.FLOAT, allowNull: true},
   tempoFecha: {type: Sequelize.FLOAT, allowNull: true},

   posAbertura1: {type: Sequelize.FLOAT, allowNull: true},
   posAbertura2: {type: Sequelize.FLOAT, allowNull: true},
   posAbertura3: {type: Sequelize.FLOAT, allowNull: true},
   posAbertura4: {type: Sequelize.FLOAT, allowNull: true},
   posAbertura5: {type: Sequelize.FLOAT, allowNull: true},
   presAbertura1: {type: Sequelize.FLOAT, allowNull: true},
   presAbertura2: {type: Sequelize.FLOAT, allowNull: true},
   presAbertura3: {type: Sequelize.FLOAT, allowNull: true},
   presAbertura4: {type: Sequelize.FLOAT, allowNull: true},
   presAbertura5: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAbertura1: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAbertura2: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAbertura3: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAbertura4: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAbertura5: {type: Sequelize.FLOAT, allowNull: true},
   resfriamento: {type: Sequelize.FLOAT, allowNull: true},
   tempoAbertura: {type: Sequelize.FLOAT, allowNull: true},

   posAvanco1: {type: Sequelize.FLOAT, allowNull: true},
   posAvanco2: {type: Sequelize.FLOAT, allowNull: true},
   posAvanco3: {type: Sequelize.FLOAT, allowNull: true},
   posRecuo1: {type: Sequelize.FLOAT, allowNull: true},
   posRecuo2: {type: Sequelize.FLOAT, allowNull: true},
   posRecuo3: {type: Sequelize.FLOAT, allowNull: true},
   presAvanco1: {type: Sequelize.FLOAT, allowNull: true},
   presAvanco2: {type: Sequelize.FLOAT, allowNull: true},
   presAvanco3: {type: Sequelize.FLOAT, allowNull: true},
   presRecuo1: {type: Sequelize.FLOAT, allowNull: true},
   presRecuo2: {type: Sequelize.FLOAT, allowNull: true},
   presRecuo3: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAvanco1: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAvanco2: {type: Sequelize.FLOAT, allowNull: true},
   fluxoAvanco3: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecuo1: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecuo2: {type: Sequelize.FLOAT, allowNull: true},
   fluxoRecuo3: {type: Sequelize.FLOAT, allowNull: true},
   atraso: {type: Sequelize.FLOAT, allowNull: true},
   batida: {type: Sequelize.FLOAT, allowNull: true},

   radialTypeEntrada1: {type: Sequelize.FLOAT, allowNull: true},
   radialTypeSaida1: {type: Sequelize.FLOAT, allowNull: true},
   radialTypeEntrada2: {type: Sequelize.FLOAT, allowNull: true},
   radialTypeSaida2: {type: Sequelize.FLOAT, allowNull: true},

   radialPresEntrada1: {type: Sequelize.FLOAT, allowNull: true},
   radialPresSaida1: {type: Sequelize.FLOAT, allowNull: true},
   radialPresEntrada2: {type: Sequelize.FLOAT, allowNull: true},
   radialPresSaida2: {type: Sequelize.FLOAT, allowNull: true},
   radialPresEntrada3: {type: Sequelize.FLOAT, allowNull: true},
   radialPresSaida3: {type: Sequelize.FLOAT, allowNull: true},

   radialFluxoEntrada1: {type: Sequelize.FLOAT, allowNull: true},
   radialFluxoSaida1: {type: Sequelize.FLOAT, allowNull: true},
   radialFluxoEntrada2: {type: Sequelize.FLOAT, allowNull: true},
   radialFluxoSaida2: {type: Sequelize.FLOAT, allowNull: true},
   radialFluxoEntrada3: {type: Sequelize.FLOAT, allowNull: true},
   radialFluxoSaida3: {type: Sequelize.FLOAT, allowNull: true},

   radialPosEntrada1: {type: Sequelize.FLOAT, allowNull: true},
   radialPosSaida1: {type: Sequelize.FLOAT, allowNull: true},
   radialPosEntrada2: {type: Sequelize.FLOAT, allowNull: true},
   radialPosSaida2: {type: Sequelize.FLOAT, allowNull: true},
   radialPosEntrada3: {type: Sequelize.FLOAT, allowNull: true},
   radialPosSaida3: {type: Sequelize.FLOAT, allowNull: true},

   radialTempoEntrada1: {type: Sequelize.FLOAT, allowNull: true},
   radialTempoSaida1: {type: Sequelize.FLOAT, allowNull: true},
   radialTempoEntrada2: {type: Sequelize.FLOAT, allowNull: true},
   radialTempoSaida2: {type: Sequelize.FLOAT, allowNull: true},
   radialTempoEntrada3: {type: Sequelize.FLOAT, allowNull: true},
   radialTempoSaida3: {type: Sequelize.FLOAT, allowNull: true},

   radialSCREntrada1: {type: Sequelize.FLOAT, allowNull: true},
   radialSCRSaida1: {type: Sequelize.FLOAT, allowNull: true},
   radialSCREntrada2: {type: Sequelize.FLOAT, allowNull: true},
   radialSCRSaida2: {type: Sequelize.FLOAT, allowNull: true},
   radialSCREntrada3: {type: Sequelize.FLOAT, allowNull: true},
   radialSCRSaida3: {type: Sequelize.FLOAT, allowNull: true},
})

Clientes.hasMany(FichaPastoreInjetores);
Moldes.hasMany(FichaPastoreInjetores);
Maquinas.hasMany(FichaPastoreInjetores);
Produtos.hasMany(FichaPastoreInjetores);
MateriaPrima.hasMany(FichaPastoreInjetores);

module.exports = FichaPastoreInjetores;