const Sequelize = require("sequelize");
const conn = require("../database/database");
const Clientes = require("../Clientes/Clientes");
const Moldes = require("../Moldes/Moldes");
const Maquinas = require("../Maquinas/Maquinas");
const Produtos = require("../Produtos/Produtos");
const MateriaPrima = require("../MateriaPrima/MateriasPrimas");

const RevisaoFichaPastorePerifericos = conn.define('revisao_perifericos_pastore',{
   revisao: {
      type: Sequelize.INTEGER,
      autoIncrement: true,
      primaryKey: true
   },
   idFichaTecnica:{
      type: Sequelize.INTEGER,
      model: 'perifericos_pastore', // <<< Note, its table's name, not object name
      key: 'id'
   },
   maq:{
      type: Sequelize.INTEGER,
      model: 'maquinas', // <<< Note, its table's name, not object name
      key: 'id'
   },
   camara1: Sequelize.FLOAT,
   camara2: Sequelize.FLOAT,
   camara3: Sequelize.FLOAT,
   camara4: Sequelize.FLOAT,
   camara5: Sequelize.FLOAT,
   camara6: Sequelize.FLOAT,
   camara7: Sequelize.FLOAT,
   camara8: Sequelize.FLOAT,
   camara9: Sequelize.FLOAT,
   camara10: Sequelize.FLOAT,
   camara11: Sequelize.FLOAT,
   camara12: Sequelize.FLOAT,
   camara13: Sequelize.FLOAT,
   camara14: Sequelize.FLOAT,
   camara15: Sequelize.FLOAT,
   camara16: Sequelize.FLOAT,
   camara17: Sequelize.FLOAT,
   camara18: Sequelize.FLOAT,
   camara19: Sequelize.FLOAT,
   camara20: Sequelize.FLOAT,
   camara21: Sequelize.FLOAT,
   camara22: Sequelize.FLOAT,
   camara23: Sequelize.FLOAT,
   camara24: Sequelize.FLOAT,
   camara25: Sequelize.FLOAT,
   camara26: Sequelize.FLOAT,
   camara27: Sequelize.FLOAT,
   camara28: Sequelize.FLOAT,
   camara29: Sequelize.FLOAT,
   camara30: Sequelize.FLOAT,
   camara31: Sequelize.FLOAT,
   camara32: Sequelize.FLOAT,
   camara33: Sequelize.FLOAT,
   camara34: Sequelize.FLOAT,
   camara35: Sequelize.FLOAT,
   camara36: Sequelize.FLOAT,
   camara37: Sequelize.FLOAT,
   camara38: Sequelize.FLOAT,
   camara39: Sequelize.FLOAT,
   camara40: Sequelize.FLOAT,
   camara41: Sequelize.FLOAT,
   camara42: Sequelize.FLOAT,
   camara43: Sequelize.FLOAT,
   camara44: Sequelize.FLOAT,
   camara45: Sequelize.FLOAT,
   camara46: Sequelize.FLOAT,
   camara47: Sequelize.FLOAT,
   camara48: Sequelize.FLOAT,
   camara49: Sequelize.FLOAT,
   camara50: Sequelize.FLOAT,
   camara51: Sequelize.FLOAT,
   camara52: Sequelize.FLOAT,
   camara53: Sequelize.FLOAT,
   camara54: Sequelize.FLOAT,
   camara55: Sequelize.FLOAT,
   camara56: Sequelize.FLOAT,
   camara57: Sequelize.FLOAT,
   camara58: Sequelize.FLOAT,
   camara59: Sequelize.FLOAT,
   camara60: Sequelize.FLOAT,
   camara61: Sequelize.FLOAT,
   camara62: Sequelize.FLOAT,
   camara63: Sequelize.FLOAT,
   camara64: Sequelize.FLOAT,
   camara65: Sequelize.FLOAT,
   camara66: Sequelize.FLOAT,
   camara67: Sequelize.FLOAT,
   camara68: Sequelize.FLOAT,
   camara69: Sequelize.FLOAT,
   camara70: Sequelize.FLOAT,
   camara71: Sequelize.FLOAT,
   camara72: Sequelize.FLOAT,
   camara73: Sequelize.FLOAT,
   camara74: Sequelize.FLOAT,
   camara75: Sequelize.FLOAT,
   camara76: Sequelize.FLOAT,
   camara77: Sequelize.FLOAT,
   camara78: Sequelize.FLOAT,
   camara79: Sequelize.FLOAT,
   camara80: Sequelize.FLOAT,
   camara81: Sequelize.FLOAT,
   camara82: Sequelize.FLOAT,
   camara83: Sequelize.FLOAT,
   camara84: Sequelize.FLOAT,
   camara85: Sequelize.FLOAT,
   camara86: Sequelize.FLOAT,
   camara87: Sequelize.FLOAT,
   camara88: Sequelize.FLOAT,
   camara89: Sequelize.FLOAT,
   camara90: Sequelize.FLOAT,
   camara91: Sequelize.FLOAT,
   camara92: Sequelize.FLOAT,
   camara93: Sequelize.FLOAT,
   camara94: Sequelize.FLOAT,
   camara95: Sequelize.FLOAT,
   camara96: Sequelize.FLOAT,
   camara97: Sequelize.FLOAT,
   camara98: Sequelize.FLOAT,
   camara99: Sequelize.FLOAT,
   camara100: Sequelize.FLOAT,
   camara101: Sequelize.FLOAT,
   camara102: Sequelize.FLOAT,
   camara103: Sequelize.FLOAT,
   camara104: Sequelize.FLOAT,
   camara105: Sequelize.FLOAT,
   camara106: Sequelize.FLOAT,
   camara107: Sequelize.FLOAT,
   camara108: Sequelize.FLOAT,
   camara109: Sequelize.FLOAT,
   camara110: Sequelize.FLOAT,
   camara111: Sequelize.FLOAT,
   camara112: Sequelize.FLOAT,
   camara113: Sequelize.FLOAT,
   camara114: Sequelize.FLOAT,
   camara115: Sequelize.FLOAT,
   camara116: Sequelize.FLOAT,
   camara117: Sequelize.FLOAT,
   camara118: Sequelize.FLOAT,
   camara119: Sequelize.FLOAT,
   camara120: Sequelize.FLOAT,
   camara121: Sequelize.FLOAT,
   camara122: Sequelize.FLOAT,
   camara123: Sequelize.FLOAT,
   camara124: Sequelize.FLOAT,
   camara125: Sequelize.FLOAT,
   camara126: Sequelize.FLOAT,
   camara127: Sequelize.FLOAT,
   camara128: Sequelize.FLOAT,
   camara129: Sequelize.FLOAT,
   camara130: Sequelize.FLOAT,
   termoparK1: {type: Sequelize.FLOAT, allowNull: true},
   termoparJ: {type: Sequelize.FLOAT, allowNull: true},
   termoparK2: {type: Sequelize.FLOAT, allowNull: true},
   
   valve1: {type: Sequelize.FLOAT, allowNull: true},
   valve2: {type: Sequelize.FLOAT, allowNull: true},
   valve3: {type: Sequelize.FLOAT, allowNull: true},
   valve4: {type: Sequelize.FLOAT, allowNull: true},
   valve5: {type: Sequelize.FLOAT, allowNull: true},
   valve6: {type: Sequelize.FLOAT, allowNull: true},
   valve7: {type: Sequelize.FLOAT, allowNull: true},
   valve8: {type: Sequelize.FLOAT, allowNull: true},
   valve9: {type: Sequelize.FLOAT, allowNull: true},
   valve10: {type: Sequelize.FLOAT, allowNull: true},
   valve11: {type: Sequelize.FLOAT, allowNull: true},
   valve12: {type: Sequelize.FLOAT, allowNull: true},
   valve13: {type: Sequelize.FLOAT, allowNull: true},
   valve14: {type: Sequelize.FLOAT, allowNull: true},
   valve15: {type: Sequelize.FLOAT, allowNull: true},
   valve16: {type: Sequelize.FLOAT, allowNull: true},
   valve17: {type: Sequelize.FLOAT, allowNull: true},
   valve18: {type: Sequelize.FLOAT, allowNull: true},
   valve19: {type: Sequelize.FLOAT, allowNull: true},
   valve20: {type: Sequelize.FLOAT, allowNull: true},
   valve21: {type: Sequelize.FLOAT, allowNull: true},
   valve22: {type: Sequelize.FLOAT, allowNull: true},
   valve23: {type: Sequelize.FLOAT, allowNull: true},
   valve24: {type: Sequelize.FLOAT, allowNull: true},
   valve25: {type: Sequelize.FLOAT, allowNull: true},
   valve26: {type: Sequelize.FLOAT, allowNull: true},
   valve27: {type: Sequelize.FLOAT, allowNull: true},
   valve28: {type: Sequelize.FLOAT, allowNull: true},
   valve29: {type: Sequelize.FLOAT, allowNull: true},
   valve30: {type: Sequelize.FLOAT, allowNull: true},
   valve31: {type: Sequelize.FLOAT, allowNull: true},
   valve32: {type: Sequelize.FLOAT, allowNull: true},
   valve33: {type: Sequelize.FLOAT, allowNull: true},
   valve34: {type: Sequelize.FLOAT, allowNull: true},
   valve35: {type: Sequelize.FLOAT, allowNull: true},
   valve36: {type: Sequelize.FLOAT, allowNull: true},
   valve37: {type: Sequelize.FLOAT, allowNull: true},
   valve38: {type: Sequelize.FLOAT, allowNull: true},
   valve39: {type: Sequelize.FLOAT, allowNull: true},
   valve40: {type: Sequelize.FLOAT, allowNull: true},
   valve41: {type: Sequelize.FLOAT, allowNull: true},
   valve42: {type: Sequelize.FLOAT, allowNull: true},
   valve43: {type: Sequelize.FLOAT, allowNull: true},
   valve44: {type: Sequelize.FLOAT, allowNull: true},
   valve45: {type: Sequelize.FLOAT, allowNull: true},
   valve46: {type: Sequelize.FLOAT, allowNull: true},
   valve47: {type: Sequelize.FLOAT, allowNull: true},
   valve48: {type: Sequelize.FLOAT, allowNull: true},
   valve49: {type: Sequelize.FLOAT, allowNull: true},
   valve50: {type: Sequelize.FLOAT, allowNull: true},
   valve51: {type: Sequelize.FLOAT, allowNull: true},
   valve52: {type: Sequelize.FLOAT, allowNull: true},
   valve53: {type: Sequelize.FLOAT, allowNull: true},
   valve54: {type: Sequelize.FLOAT, allowNull: true},
   valve55: {type: Sequelize.FLOAT, allowNull: true},
   valve56: {type: Sequelize.FLOAT, allowNull: true},
   valve57: {type: Sequelize.FLOAT, allowNull: true},
   valve58: {type: Sequelize.FLOAT, allowNull: true},
   valve59: {type: Sequelize.FLOAT, allowNull: true},
   valve60: {type: Sequelize.FLOAT, allowNull: true},
   valve61: {type: Sequelize.FLOAT, allowNull: true},
   valve62: {type: Sequelize.FLOAT, allowNull: true},
   valve63: {type: Sequelize.FLOAT, allowNull: true},
   valve64: {type: Sequelize.FLOAT, allowNull: true},
   valve65: {type: Sequelize.FLOAT, allowNull: true},
   valve66: {type: Sequelize.FLOAT, allowNull: true},
   valve67: {type: Sequelize.FLOAT, allowNull: true},
   valve68: {type: Sequelize.FLOAT, allowNull: true},
   valve69: {type: Sequelize.FLOAT, allowNull: true},
   valve70: {type: Sequelize.FLOAT, allowNull: true},
   valve71: {type: Sequelize.FLOAT, allowNull: true},
   valve72: {type: Sequelize.FLOAT, allowNull: true},
   valve73: {type: Sequelize.FLOAT, allowNull: true},
   valve74: {type: Sequelize.FLOAT, allowNull: true},
   valve75: {type: Sequelize.FLOAT, allowNull: true},
   valve76: {type: Sequelize.FLOAT, allowNull: true},
   valve77: {type: Sequelize.FLOAT, allowNull: true},
   valve78: {type: Sequelize.FLOAT, allowNull: true},
   valve79: {type: Sequelize.FLOAT, allowNull: true},
   valve80: {type: Sequelize.FLOAT, allowNull: true},
   valve81: {type: Sequelize.FLOAT, allowNull: true},
   valve82: {type: Sequelize.FLOAT, allowNull: true},
   valve83: {type: Sequelize.FLOAT, allowNull: true},
   valve84: {type: Sequelize.FLOAT, allowNull: true},
   valve85: {type: Sequelize.FLOAT, allowNull: true},
   valve86: {type: Sequelize.FLOAT, allowNull: true},
   valve87: {type: Sequelize.FLOAT, allowNull: true},
   valve88: {type: Sequelize.FLOAT, allowNull: true},
   valve89: {type: Sequelize.FLOAT, allowNull: true},
   valve90: {type: Sequelize.FLOAT, allowNull: true},
   valve91: {type: Sequelize.FLOAT, allowNull: true},
   valve92: {type: Sequelize.FLOAT, allowNull: true},
   valve93: {type: Sequelize.FLOAT, allowNull: true},
   valve94: {type: Sequelize.FLOAT, allowNull: true},
   valve95: {type: Sequelize.FLOAT, allowNull: true},
   valve96: {type: Sequelize.FLOAT, allowNull: true},
   valve97: {type: Sequelize.FLOAT, allowNull: true},
   valve98: {type: Sequelize.FLOAT, allowNull: true},
   valve99: {type: Sequelize.FLOAT, allowNull: true},
   valve100: {type: Sequelize.FLOAT, allowNull: true},
   valve101: {type: Sequelize.FLOAT, allowNull: true},
   valve102: {type: Sequelize.FLOAT, allowNull: true},
   valve103: {type: Sequelize.FLOAT, allowNull: true},
   valve104: {type: Sequelize.FLOAT, allowNull: true},
   valve105: {type: Sequelize.FLOAT, allowNull: true},
   valve106: {type: Sequelize.FLOAT, allowNull: true},
   valve107: {type: Sequelize.FLOAT, allowNull: true},
   valve108: {type: Sequelize.FLOAT, allowNull: true},
   valve109: {type: Sequelize.FLOAT, allowNull: true},
   valve110: {type: Sequelize.FLOAT, allowNull: true},
   valve111: {type: Sequelize.FLOAT, allowNull: true},
   valve112: {type: Sequelize.FLOAT, allowNull: true},
   valve113: {type: Sequelize.FLOAT, allowNull: true},
   valve114: {type: Sequelize.FLOAT, allowNull: true},
   valve115: {type: Sequelize.FLOAT, allowNull: true},
   valve116: {type: Sequelize.FLOAT, allowNull: true},
   valve117: {type: Sequelize.FLOAT, allowNull: true},
   valve118: {type: Sequelize.FLOAT, allowNull: true},
   valve119: {type: Sequelize.FLOAT, allowNull: true},
   valve120: {type: Sequelize.FLOAT, allowNull: true},
   valve121: {type: Sequelize.FLOAT, allowNull: true},
   valve122: {type: Sequelize.FLOAT, allowNull: true},
   valve123: {type: Sequelize.FLOAT, allowNull: true},
   valve124: {type: Sequelize.FLOAT, allowNull: true},
   valve125: {type: Sequelize.FLOAT, allowNull: true},
   valve126: {type: Sequelize.FLOAT, allowNull: true},
   valve127: {type: Sequelize.FLOAT, allowNull: true},
   valve128: {type: Sequelize.FLOAT, allowNull: true},
   valve129: {type: Sequelize.FLOAT, allowNull: true},
   valve130: {type: Sequelize.FLOAT, allowNull: true},
   valve131: {type: Sequelize.FLOAT, allowNull: true},
   valve132: {type: Sequelize.FLOAT, allowNull: true},
   valve133: {type: Sequelize.FLOAT, allowNull: true},
   valve134: {type: Sequelize.FLOAT, allowNull: true},
   valve135: {type: Sequelize.FLOAT, allowNull: true},
   valve136: {type: Sequelize.FLOAT, allowNull: true},
   valve137: {type: Sequelize.FLOAT, allowNull: true},
   valve138: {type: Sequelize.FLOAT, allowNull: true},
   valve139: {type: Sequelize.FLOAT, allowNull: true},
   valve140: {type: Sequelize.FLOAT, allowNull: true},
   valve141: {type: Sequelize.FLOAT, allowNull: true},
   valve142: {type: Sequelize.FLOAT, allowNull: true},
   valve143: {type: Sequelize.FLOAT, allowNull: true},
   valve144: {type: Sequelize.FLOAT, allowNull: true},
   valve145: {type: Sequelize.FLOAT, allowNull: true},
   valve146: {type: Sequelize.FLOAT, allowNull: true},
   valve147: {type: Sequelize.FLOAT, allowNull: true},
   valve148: {type: Sequelize.FLOAT, allowNull: true},
   valve149: {type: Sequelize.FLOAT, allowNull: true},
   valve150: {type: Sequelize.FLOAT, allowNull: true},
   valve151: {type: Sequelize.FLOAT, allowNull: true},
   valve152: {type: Sequelize.FLOAT, allowNull: true},
   valve153: {type: Sequelize.FLOAT, allowNull: true},
   valve154: {type: Sequelize.FLOAT, allowNull: true},
   valve155: {type: Sequelize.FLOAT, allowNull: true},
   valve156: {type: Sequelize.FLOAT, allowNull: true},
   valve157: {type: Sequelize.FLOAT, allowNull: true},
   valve158: {type: Sequelize.FLOAT, allowNull: true},
   valve159: {type: Sequelize.FLOAT, allowNull: true},
   valve160: {type: Sequelize.FLOAT, allowNull: true},
   valve161: {type: Sequelize.FLOAT, allowNull: true},
   valve162: {type: Sequelize.FLOAT, allowNull: true},
   valve163: {type: Sequelize.FLOAT, allowNull: true},
   valve164: {type: Sequelize.FLOAT, allowNull: true},
   valve165: {type: Sequelize.FLOAT, allowNull: true},
   valve166: {type: Sequelize.FLOAT, allowNull: true},
   valve167: {type: Sequelize.FLOAT, allowNull: true},
   valve168: {type: Sequelize.FLOAT, allowNull: true},
   valve169: {type: Sequelize.FLOAT, allowNull: true},
   valve170: {type: Sequelize.FLOAT, allowNull: true},
   valve171: {type: Sequelize.FLOAT, allowNull: true},
   valve172: {type: Sequelize.FLOAT, allowNull: true},
   valve173: {type: Sequelize.FLOAT, allowNull: true},
   valve174: {type: Sequelize.FLOAT, allowNull: true},
   valve175: {type: Sequelize.FLOAT, allowNull: true},
   valve176: {type: Sequelize.FLOAT, allowNull: true},
   valve177: {type: Sequelize.FLOAT, allowNull: true},
   valve178: {type: Sequelize.FLOAT, allowNull: true},
   valve179: {type: Sequelize.FLOAT, allowNull: true},
   valve180: {type: Sequelize.FLOAT, allowNull: true},
   voltagem: {type: Sequelize.FLOAT, allowNull: true},

   refrLadoFixo1: Sequelize.FLOAT,
   refrLadoFixo2: Sequelize.FLOAT,
   refrLadoMovel1: Sequelize.FLOAT,
   refrLadoMovel2: Sequelize.FLOAT,

   vaporLadoFixo1: Sequelize.FLOAT,
   vaporLadoFixo2: Sequelize.FLOAT,
})

Clientes.hasMany(RevisaoFichaPastorePerifericos);
Moldes.hasMany(RevisaoFichaPastorePerifericos);
Maquinas.hasMany(RevisaoFichaPastorePerifericos);
Produtos.hasMany(RevisaoFichaPastorePerifericos);
MateriaPrima.hasMany(RevisaoFichaPastorePerifericos);


module.exports = RevisaoFichaPastorePerifericos;