
const express = require("express");
const router = express.Router();
var nodemailer = require('nodemailer');
const dotenv = require('dotenv');
const path = require('path');
dotenv.config(); //PARA TESTES, COMENTE ESSE E DESCOMENTE O DEBAIXO

// dotenv.config({path: path.resolve(__dirname, '../.env.example')});

const ParametrosReaisHaitianJupyter = require("../ParametrosTempoReal/ParametrosReaisHaitianJupyter");

var listParametros = ["TEMPERATURA_ZONA_1",
"TEMPERATURA_ZONA_2",
"TEMPERATURA_ZONA_3",
"TEMPERATURA_ZONA_4",
"TEMPERATURA_ZONA_5",
"TEMPERATURA_ZONA_6",
"TEMPERATURA_ZONA_7",
"TEMPERATURA_BICO",
"PRESSAO_INJEC_MAX",
"PROTEC_MOLDE_MAX",
"FORCA_FECHAMENTO",
"TEMPO_INJEC_REAL",
"TEMPO_RECALQUE",
"TEMPO_ABERTURA_PLACA_MOVEL",
"TEMPO_FECHAMENTO_PLACA_MOVEL",
"TEMPO_EXTRACAO",
"TEMPO_DOSAGEM",
"TEMPO_RESFRIAMENTO",
"TEMPO_CICLO",
"VELOCIDADE_INJECAO_1",
"VELOCIDADE_INJECAO_1_mm",
"VELOCIDADE_INJECAO_2",
"VELOCIDADE_INJECAO_2_mm",
"VELOCIDADE_INJECAO_3 ",
"VELOCIDADE_INJECAO_3_mm",
"VELOCIDADE_INJECAO_4",
"VELOCIDADE_INJECAO_4_mm",
"VELOCIDADE_INJECAO_5",
"VELOCIDADE_INJECAO_5_mm",
"VELOCIDADE_INJECAO_6",
"VELOCIDADE_INJECAO_6_mm",
"VELOCIDADE_INJECAO_7",
"VELOCIDADE_INJECAO_7_mm",
"VELOCIDADE_INJECAO_8",
"VELOCIDADE_INJECAO_8_mm",
"VELOCIDADE_INJECAO_9",
"VELOCIDADE_INJECAO_9_mm",
"VELOCIDADE_INJECAO_10",
"VELOCIDADE_INJECAO_10_mm",
"RECALQUE_PRESSAO_1",
"RECALQUE_TEMPO_1",
"RECALQUE_FLUXO_1",
"RECALQUE_PRESSAO_2",
"RECALQUE_TEMPO_2",
"RECALQUE_FLUXO_2",
"RECALQUE_PRESSAO_3",
"RECALQUE_TEMPO_3",
"RECALQUE_FLUXO_3",
"RECALQUE_PRESSAO_4",
"RECALQUE_TEMPO_4",
"RECALQUE_FLUXO_4",
"RECALQUE_PRESSAO_5",
"RECALQUE_TEMPO_5",
"RECALQUE_FLUXO_5",
"VALVE_GATE_DELAY_TIME_1",
"VALVE_GATE_DELAY_TIME_2",
"VALVE_GATE_DELAY_TIME_3",
"VALVE_GATE_DELAY_TIME_4",
"VALVE_GATE_DELAY_TIME_5",
"VALVE_GATE_ACTIVE_TIME_1",
"VALVE_GATE_ACTIVE_TIME_2",
"VALVE_GATE_ACTIVE_TIME_3",
"VALVE_GATE_ACTIVE_TIME_4",
"VALVE_GATE_ACTIVE_TIME_5",
"SQ_RETARDO_11",
"CAMARA_QUENTE_TEMPERATURA_1",
"CAMARA_QUENTE_TEMPERATURA_2",
"CAMARA_QUENTE_TEMPERATURA_3",
"CAMARA_QUENTE_TEMPERATURA_4",
"CAMARA_QUENTE_TEMPERATURA_5",
"CAMARA_QUENTE_TEMPERATURA_6",
"CAMARA_QUENTE_TEMPERATURA_7",
"CAMARA_QUENTE_TEMPERATURA_8",
"CAMARA_QUENTE_TEMPERATURA_9",
"CAMARA_QUENTE_TEMPERATURA_10",
"CAMARA_QUENTE_TEMPERATURA_11",
"CAMARA_QUENTE_TEMPERATURA_12",
"CAMARA_QUENTE_TEMPERATURA_13",
"CAMARA_QUENTE_TEMPERATURA_14",
"CAMARA_QUENTE_TEMPERATURA_15",
"CAMARA_QUENTE_TEMPERATURA_16",
"DOSAGEM_PARTIDA_1",
"DOSAGEM_PRESSAO_1",
"DOSAGEM_FLUXO_1",
"DOSAGEM_CONTRAPRESSAO_1",
"DOSAGEM_PARTIDA_2",
"DOSAGEM_PRESSAO_2",
"DOSAGEM_FLUXO_2",
"DOSAGEM_CONTRAPRESSAO_2",
"DOSAGEM_PARTIDA_3",
"DOSAGEM_PRESSAO_3",
"DOSAGEM_FLUXO_3",
"DOSAGEM_CONTRAPRESSAO_3",
"DOSAGEM_PARTIDA_4",
"DOSAGEM_PRESSAO_4",
"DOSAGEM_FLUXO_4",
"DOSAGEM_CONTRAPRESSAO_4",
"DOSAGEM_PARTIDA_5",
"DOSAGEM_PRESSAO_5",
"DOSAGEM_FLUXO_5",
"DOSAGEM_CONTRAPRESSAO_5",
"INJECAO_POSICAO_1",
"INJECAO_POSICAO_2",
"INJECAO_POSICAO_3",
"INJECAO_POSICAO_4",
"INJECAO_POSICAO_5",
"INJECAO_PRESSAO_1",
"INJECAO_PRESSAO_2",
"INJECAO_PRESSAO_3",
"INJECAO_PRESSAO_4",
"INJECAO_PRESSAO_5",
"INJECAO_FLUXO_1",
"INJECAO_FLUXO_2",
"INJECAO_FLUXO_3",
"INJECAO_FLUXO_4",
"INJECAO_FLUXO_5",
"TEMPO_DISPARO",
"TEMPO_INJECAO",
"POSICAO_RECALQUE",
"CURSO_DOSAGEM",
"RPM_ROSCA",
"CONTRA_PRESS_MAXIMA",
"FECHAMENTO_POSICAO_1",
"FECHAMENTO_POSICAO_2",
"FECHAMENTO_POSICAO_3",
"FECHAMENTO_POSICAO_PROTECAO_MOLDE",
"FECHAMENTO_POSICAO_ALTA_PRESSAO",
"FECHAMENTO_PRESSAO_1",
"FECHAMENTO_PRESSAO_2",
"FECHAMENTO_PRESSAO_3",
"FECHAMENTO_PRESSAO_PROTECAO_MOLDE",
"FECHAMENTO_PRESSAO_ALTA_PRESSAO",
"FECHAMENTO_FLUXO_1",
"FECHAMENTO_FLUXO_2",
"FECHAMENTO_FLUXO_3",
"FECHAMENTO_FLUXO_PROTECAO_MOLDE",
"FECHAMENTO_FLUXO_ALTA_PRESSAO",
"TEMPO_PROTECAO_MOLDE",
"TEMPO_FECHAMENTO",
"ABERTURA_POSICAO_1",
"ABERTURA_POSICAO_2",
"ABERTURA_POSICAO_3",
"ABERTURA_POSICAO_4",
"ABERTURA_POSICAO_5",
"ABERTURA_PRESSAO_1",
"ABERTURA_PRESSAO_2",
"ABERTURA_PRESSAO_3",
"ABERTURA_PRESSAO_4",
"ABERTURA_PRESSAO_5",
"ABERTURA_FLUXO_1",
"ABERTURA_FLUXO_2",
"ABERTURA_FLUXO_3",
"ABERTURA_FLUXO_4",
"ABERTURA_FLUXO_5",
"TEMPO_RESFRIAMENT0",
"TEMPO_ABERTURA",
"EXTRACAO_POSICAO_AVANCO_1",
"EXTRACAO_POSICAO_AVANCO_2",
"EXTRACAO_POSICAO_AVANCO_3",
"EXTRACAO_POSICAO_RECUO_1",
"EXTRACAO_POSICAO_RECUO_2",
"EXTRACAO_POSICAO_RECUO_3",
"EXTRACAO_PRESSAO_AVANCO_1",
"EXTRACAO_PRESSAO_AVANCO_2",
"EXTRACAO_PRESSAO_AVANCO_3",
"EXTRACAO_PRESSAO_RECUO_1",
"EXTRACAO_PRESSAO_RECUO_2",
"EXTRACAO_PRESSAO_RECUO_3",
"EXTRACAO_FLUXO_AVANCO_1",
"EXTRACAO_FLUXO_AVANCO_2",
"EXTRACAO_FLUXO_AVANCO_3",
"EXTRACAO_FLUXO_RECUO_1",
"EXTRACAO_FLUXO_RECUO_2",
"EXTRACAO_FLUXO_RECUO_3",
"RADIAL_PRESSAO_ENTRADA_1",
"RADIAL_PRESSAO_ENTRADA_2",
"RADIAL_PRESSAO_ENTRADA_3",
"RADIAL_PRESSAO_SAIDA_1",
"RADIAL_PRESSAO_SAIDA_2",
"RADIAL_PRESSAO_SAIDA_3",
"RADIAL_FLUXO_ENTRADA_1",
"RADIAL_FLUXO_ENTRADA_2",
"RADIAL_FLUXO_ENTRADA_3",
"RADIAL_FLUXO_SAIDA_1",
"RADIAL_FLUXO_SAIDA_2",
"RADIAL_FLUXO_SAIDA_3",
"RADIAL_ACT_POSICAO_ENTRADA_1",
"RADIAL_ACT_POSICAO_ENTRADA_2",
"RADIAL_ACT_POSICAO_ENTRADA_3",
"RADIAL_ACT_POSICAO_SAIDA_1",
"RADIAL_ACT_POSICAO_SAIDA_2",
"RADIAL_ACT_POSICAO_SAIDA_3",
"RADIAL_ACT_TEMPO_ENTRADA_1",
"RADIAL_ACT_TEMPO_ENTRADA_2",
"RADIAL_ACT_TEMPO_ENTRADA_3",
"RADIAL_ACT_TEMPO_SAIDA_1",
"RADIAL_ACT_TEMPO_SAIDA_2",
"RADIAL_ACT_TEMPO_SAIDA_3",
"RADIAL_SCRCOUNT_ENTRADA_1",
"RADIAL_SCRCOUNT_ENTRADA_2",
"RADIAL_SCRCOUNT_ENTRADA_3",
"RADIAL_SCRCOUNT_SAIDA_1",
"RADIAL_SCRCOUNT_SAIDA_2",
"RADIAL_SCRCOUNT_SAIDA_3",
"NUMERO_REPETICOES",
"REF_MOLDE_LF",
"REF_MOLDE_LM",
"VAP_MINIMO",
"VAP_MAXIMO",
"PROG_MACHO_FUNC_E1",
"PROG_MACHO_FUNC_S1",
"PROG_MACHO_FUNC_E2",
"PROG_MACHO_FUNC_S2",
"PROG_MACHO_POSICAO_E1",
"PROG_MACHO_POSICAO_S1",
"PROG_MACHO_POSICAO_E2",
"PROG_MACHO_POSICAO_S2",
"PROG_MACHO_PARADA_E1",
"PROG_MACHO_PARADA_S1",
"PROG_MACHO_PARADA_E2",
"PROG_MACHO_PARADA_S2",
"PROG_MACHO_CDENTRO_E1",
"PROG_MACHO_CDENTRO_S1",
"PROG_MACHO_CDENTRO_E2",
"PROG_MACHO_CDENTRO_S2",
"PROG_MACHO_CFORA_E1",
"PROG_MACHO_CFORA_S1",
"PROG_MACHO_CFORA_E2",
"PROG_MACHO_CFORA_S2",
"PROG_MACHO_RETARDO_E1",
"PROG_MACHO_RETARDO_S1",
"PROG_MACHO_RETARDO_E2",
"PROG_MACHO_RETARDO_S2",
"PROG_MACHO_TATUACAO_E1",
"PROG_MACHO_TATUACAO_S1",
"PROG_MACHO_TATUACAO_E2",
"PROG_MACHO_TATUACAO_S2",
"PROG_MACHO_PRESSAO_E1",
"PROG_MACHO_PRESSAO_S1",
"PROG_MACHO_PRESSAO_E2",
"PROG_MACHO_PRESSAO_S2",
"PROG_MACHO_VELOCIDADE_E1",
"PROG_MACHO_VELOCIDADE_S1",
"PROG_MACHO_VELOCIDADE_E2",
"PROG_MACHO_VELOCIDADE_S2",
"PROG_MACHO_DETENTE_E1",
"PROG_MACHO_DETENTE_S1",
"PROG_MACHO_DETENTE_E2",
"PROG_MACHO_DETENTE_S2",
"TEMPERATURA_AGUA_TORRE", 
"TEMPERATURA_AGUA_GELADA",
"PRESSAO_AGUA_TORRE",
"PRESSAO_AGUA_GELADA"
 ]

router.get("/trigger",  (req,res) => {

    var transporter = nodemailer.createTransport({
        host: 'smtp.gmail.com',
        secure: false, // use SSL
        port: 587,
        auth: {
          user: 'wmmailcentral@gmail.com',
          pass: 'marcelft131291'
        },        
      tls: {
          rejectUnauthorized: false
      }
      });
      
      var mailOptions = {
        from: 'wmmailcentral@gmail.com',
        to: process.env.SEND_EMAIL_TO,
        subject: 'WM ALERTA',
        text: 'Parâmetros tendendo a sair dos limites esperados'
      };
      
      transporter.sendMail(mailOptions, function(error, info){
        if (error) {
          console.log(error);
        } else {
          console.log('Email sent: ' + info.response);
        }
      });

    res.redirect("/fichas")
 
     
 })

 router.get("/activateRules",  (req,res) => {




})



function rule1(){

  ParametrosReaisHaitianJupyter.findAll(
    { limit: 30, order: [ [ 'createdAt', 'DESC' ]] }
    ).then( parametros => {

      for(var j =1; j < parametros.length-4; j++){
        
        var listaParametros = [];

        for(var i =0; i < parametros.length; i++){
          
          listaParametros.push(parametros[i][j])
        }

        let desvioPadrao = calculaDesvioPadrao(listaParametros);
        console.log(desvioPadrao);
      }
      


  })
  

}

 function calculaDesvioPadrao(){
    let media = lista.reduce((total, valor) => total+valor/lista.length, 0);
    let variancia = lista.reduce((total, valor) => total + Math.pow(media - valor, 2)/lista.length, 0);
    let desvioPadrao = Math.sqrt(variancia);

    return desvioPadrao;
 }



 
module.exports = { router };
